# ===== \u30ed\u30fc\u30ab\u30ebDB\u4e0a\u66f8\u304d =====
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/expense_workflow_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
spring.datasource.username=root
spring.datasource.password=

# ===== Cookie\uff08http\u306a\u306e\u3067secure\u4e0d\u8981\uff09=====
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=false